### ISSUE TITLE
Accessibility issue with Democracy page

### ISSUE THREAD

**Issue by nylen** [ClassicPress/ClassicPress-Network#14]
@KTS915 [says](https://classicpress.slack.com/archives/CCY0Y5823/p1540433224000100):

> Just an update on accessibility on the ClassicPress website. @senlin and I have fixed most of the accessibility issues, but there is a big one left that we can't fix while we use Elementor. The problem is on this page: https://www.classicpress.net/democracy/ and the problem lies with the accordion after the heading "Our democratic structure, rights & responsibilities".
>
> There are actually two problems with this. (I initially thought it was just one, but actually things are much worse than I thought.) The first is that Elementor assigns a tabindex to each section within the accordion, and that tabindex corresponds with the section's id. This means anyone using a screenreader gets taken straight to those sections before anything else on the page, and only gets to things like the menu afterwards. That is so disorientating as to probably make the page unusable.
>
> But it's actually worse than that. Because there is no way for a screenreader user actually to access the content within each section! They can only read the title. This has been reported previously, but no fix has been forthcoming. See https://github.com/pojome/elementor/issues/3576

**Comment by KTS915** [comment]
There is bound to be more than one way to fix this, but my suggestion would be to use the FAQ Concertina plugin: https://wordpress.org/plugins/faq-concertina/

That uses a CPT for the accordion, with the title and content of each section becoming the title and content of the CPT. I recommend it because I wrote the code to make the plugin accessible, and use the plugin myself on numerous sites where accessibility is a legal requirement. The plugin is lightweight and has a neat UI where it would be easy to set the font colors to match the ClassicPress website.

**Comment by nylen** [comment]
That would work, but I wonder: do we really need to use an accordion for this?

**Comment by KTS915** [comment]
@senlin and I wondered about that too. Without an accordion, the page would get rather long.

**Comment by senlin** [comment]
Given the fact that the site is going to get a makeover within a few weeks, my suggestion would be to remove the whole accordion thing for now. Yes it will make the page rather long, but so be it. That is at least better than a page's content that cannot be read, right?

Say the word and I will fix it.

**Comment by KTS915** [comment]
Yes, you are 100% right, Pieter!

**Comment by senlin** [comment]
Done!

**Comment by nylen** [comment]
Thanks for reporting & fixing this.
